export const themes = {
  default: {
    name: 'EntertainHub',
    'color-primary': '#3b82f6',
    'color-secondary': '#8b5cf6',
    'color-background': '#0a0f1e',
    'color-surface': '#111827',
    'color-text': '#ffffff',
    'color-accent': '#60a5fa',
    cardStyle: 'rounded-xl',
    font: 'font-sans',
  },
  netflix: {
    name: 'Netflix',
    'color-primary': '#e50914',
    'color-secondary': '#b81d24',
    'color-background': '#141414',
    'color-surface': '#1f1f1f',
    'color-text': '#ffffff',
    'color-accent': '#e50914',
    cardStyle: 'rounded-sm',
    font: 'font-sans',
  },
  disney: {
    name: 'Disney+',
    'color-primary': '#0063e5',
    'color-secondary': '#0483ee',
    'color-background': '#040714',
    'color-surface': '#0c1221',
    'color-text': '#f9f9f9',
    'color-accent': '#4db5ff',
    cardStyle: 'rounded-2xl',
    font: 'font-sans',
  },
  hbo: {
    name: 'HBO Max',
    'color-primary': '#8b00ff',
    'color-secondary': '#6a0dad',
    'color-background': '#0d0d0d',
    'color-surface': '#1a1a2e',
    'color-text': '#ffffff',
    'color-accent': '#b44fff',
    cardStyle: 'rounded-lg',
    font: 'font-sans',
  },
  spotify: {
    name: 'Spotify',
    'color-primary': '#1db954',
    'color-secondary': '#1ed760',
    'color-background': '#121212',
    'color-surface': '#181818',
    'color-text': '#ffffff',
    'color-accent': '#1db954',
    cardStyle: 'rounded-full',
    font: 'font-sans',
  },
  osn: {
    name: 'OSN+',
    'color-primary': '#00a8e0',
    'color-secondary': '#0077b6',
    'color-background': '#020b18',
    'color-surface': '#051923',
    'color-text': '#ffffff',
    'color-accent': '#00c8ff',
    cardStyle: 'rounded-xl',
    font: 'font-sans',
  },
};
